[package]
name = "hopper"
version = "0.1.0"
license = "AGPL-3.0-or-later"
edition = "2021"

[dependencies]
confy = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
